language: python
python:
  - "3.4"
env:
  - DJANGO=1.8.1
install:
  - pip install coverage flake8
  - pip install Django==$DJANGO
  - pip install -e .
before_script:
  - python manage.py syncdb --noinput
script:
  - flake8 command_scheduler
  - PYTHONPATH=. coverage run --branch --source=command_scheduler python test_project/manage.py test command_scheduler
  - coverage report
